// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuVWc__6dbAiO0N9Wst1oyql2WhMprs34',
    appId: '1:339947601263:web:70fa7c19b3bfcda26abc9a',
    messagingSenderId: '339947601263',
    projectId: 'smartcondominium-6d603',
    authDomain: 'smartcondominium-6d603.firebaseapp.com',
    storageBucket: 'smartcondominium-6d603.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4BfeG37KMoBsqydoJIUrwsjar1-nNLuc',
    appId: '1:339947601263:android:019e0ca9befa66a46abc9a',
    messagingSenderId: '339947601263',
    projectId: 'smartcondominium-6d603',
    storageBucket: 'smartcondominium-6d603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQn83tmUC_l3-gMKe1rrhKadC_8FXkqPw',
    appId: '1:339947601263:ios:5f8a9100b618e9ca6abc9a',
    messagingSenderId: '339947601263',
    projectId: 'smartcondominium-6d603',
    storageBucket: 'smartcondominium-6d603.firebasestorage.app',
    iosBundleId: 'com.example.smartCondominium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQn83tmUC_l3-gMKe1rrhKadC_8FXkqPw',
    appId: '1:339947601263:ios:5f8a9100b618e9ca6abc9a',
    messagingSenderId: '339947601263',
    projectId: 'smartcondominium-6d603',
    storageBucket: 'smartcondominium-6d603.firebasestorage.app',
    iosBundleId: 'com.example.smartCondominium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuVWc__6dbAiO0N9Wst1oyql2WhMprs34',
    appId: '1:339947601263:web:e6868a8659805b766abc9a',
    messagingSenderId: '339947601263',
    projectId: 'smartcondominium-6d603',
    authDomain: 'smartcondominium-6d603.firebaseapp.com',
    storageBucket: 'smartcondominium-6d603.firebasestorage.app',
  );
}
